tvOS support
getditto/DittoSwiftTools pull request #82
Opened 2024-02-20 17:19 UTC by ErikEverson

Waiting on release with tvOS support before merging. 

- Added tvOS support by flagging out features that are not available for tvOS.

2024-02-20 20:34 UTC, bplattenburg requested changes

2024-02-20 20:34 UTC, bplattenburg commented on Package.swift
> +        .package(path: "../DittoSwiftPackage"),
I think this needs to change back to the git URL rather than a local path

2024-02-20 20:35 UTC, bplattenburg commented on Package.swift
> +        .package(path: "../DittoSwiftPackage"),
(Which I assume is because this is a draft)

2024-05-24 15:23 UTC, ErikEverson commented
Here are screen shots of before 
![Simulator Screenshot - Apple TV 4K - 2024-05-24 at 09 13 55](https://github.com/getditto/DittoSwiftTools/assets/32311723/c2258af1-56b5-4d13-b5ed-0eb861803346)
![Simulator Screenshot - Apple TV 4K - 2024-05-24 at 09 14 13](https://github.com/getditto/DittoSwiftTools/assets/32311723/e556461a-a17d-48a2-afeb-426e30c23e79)
![Simulator Screenshot - Apple TV 4K - 2024-05-24 at 09 14 39](https://github.com/getditto/DittoSwiftTools/assets/32311723/b47b22aa-ac60-4aaf-87e7-82bd623c25ab)
![Simulator Screenshot - Apple TV 4K - 2024-05-24 at 09 15 16](https://github.com/getditto/DittoSwiftTools/assets/32311723/f7af4862-0b88-47eb-b111-5f989c650e73)
![Simulator Screenshot - Apple TV 4K - 2024-05-24 at 09 15 36](https://github.com/getditto/DittoSwiftTools/assets/32311723/b8cac8b7-64ae-4390-a002-01898d78a13a)
![Simulator Screenshot - Apple TV 4K - 2024-05-24 at 09 15 58](https://github.com/getditto/DittoSwiftTools/assets/32311723/454d5955-5435-4d3c-b064-d6bbea0180e1)
![Simulator Screenshot - Apple TV 4K - 2024-05-24 at 09 16 28](https://github.com/getditto/DittoSwiftTools/assets/32311723/8554001d-1577-4fb6-88d2-54e96bad1aa7)
![Simulator Screenshot - Apple TV 4K - 2024-05-24 at 09 16 41](https://github.com/getditto/DittoSwiftTools/assets/32311723/e6dfb1b0-b15c-4f64-8acf-a9c9c84c5f3b)
![Simulator Screenshot - Apple TV 4K - 2024-05-24 at 09 17 04](https://github.com/getditto/DittoSwiftTools/assets/32311723/a8680473-08e2-4baf-8fa5-a2452abb4095)
![Simulator Screenshot - iPad (10th generation) - 2024-05-24 at 09 13 57](https://github.com/getditto/DittoSwiftTools/assets/32311723/af3938c0-5455-46cb-adf0-b9d8b60ce45b)
![Simulator Screenshot - iPad (10th generation) - 2024-05-24 at 09 14 14](https://github.com/getditto/DittoSwiftTools/assets/32311723/1d9f68ba-f82f-48af-81b4-e6f4491d6794)
![Simulator Screenshot - iPad (10th generation) - 2024-05-24 at 09 14 40](https://github.com/getditto/DittoSwiftTools/assets/32311723/5232851e-775c-4d47-8464-f57eeca31356)
![Simulator Screenshot - iPad (10th generation) - 2024-05-24 at 09 15 18](https://github.com/getditto/DittoSwiftTools/assets/32311723/78da5623-8d80-48b8-9d94-23647e1d7f72)
![Simulator Screenshot - iPad (10th generation) - 2024-05-24 at 09 15 37](https://github.com/getditto/DittoSwiftTools/assets/32311723/69fb2de1-31df-4c5a-b553-34162eb56e96)
![Simulator Screenshot - iPad (10th generation) - 2024-05-24 at 09 15 59](https://github.com/getditto/DittoSwiftTools/assets/32311723/d9d80a37-5e96-485f-81b7-1d07f3f3e512)
![Simulator Screenshot - iPad (10th generation) - 2024-05-24 at 09 16 29](https://github.com/getditto/DittoSwiftTools/assets/32311723/5040e78e-0791-41c5-8489-c9b33d5a5aa4)
![Simulator Screenshot - iPad (10th generation) - 2024-05-24 at 09 16 42](https://github.com/getditto/DittoSwiftTools/assets/32311723/5d1e7cf9-a1e4-4573-807c-4d34fcba135c)
![Simulator Screenshot - iPad (10th generation) - 2024-05-24 at 09 16 52](https://github.com/getditto/DittoSwiftTools/assets/32311723/38532b06-371b-4227-84ee-006138f56ecb)
![Simulator Screenshot - iPhone Xs - 2024-05-24 at 09 13 58](https://github.com/getditto/DittoSwiftTools/assets/32311723/a94eda3c-8270-423d-a9bb-0476788ba6f6)
![Simulator Screenshot - iPhone Xs - 2024-05-24 at 09 14 18](https://github.com/getditto/DittoSwiftTools/assets/32311723/fe746a30-a9ea-4aaf-b86f-191ab96ccd3c)
![Simulator Screenshot - iPhone Xs - 2024-05-24 at 09 14 41](https://github.com/getditto/DittoSwiftTools/assets/32311723/d0c0bac4-e103-477d-808d-2a1b45e01a06)
![Simulator Screenshot - iPhone Xs - 2024-05-24 at 09 15 19](https://github.com/getditto/DittoSwiftTools/assets/32311723/80110209-e8f9-4b82-9c72-7ea3a8cad475)
![Simulator Screenshot - iPhone Xs - 2024-05-24 at 09 15 38](https://github.com/getditto/DittoSwiftTools/assets/32311723/e1ff297d-9597-4973-bfcb-2340030fd74a)
![Simulator Screenshot - iPhone Xs - 2024-05-24 at 09 16 00](https://github.com/getditto/DittoSwiftTools/assets/32311723/9929aa31-9004-4673-beee-784477a54946)
![Simulator Screenshot - iPhone Xs - 2024-05-24 at 09 16 30](https://github.com/getditto/DittoSwiftTools/assets/32311723/d224ee07-2a97-4c1e-a015-088b77059309)
![Simulator Screenshot - iPhone Xs - 2024-05-24 at 09 16 43](https://github.com/getditto/DittoSwiftTools/assets/32311723/21190ae5-d737-4e29-bf58-dfefd6783db1)

2024-05-24 15:25 UTC, ErikEverson commented
Here are screen shots of the fixes after

![Simulator Screenshot - Apple TV 4K - 2024-05-24 at 08 55 20](https://github.com/getditto/DittoSwiftTools/assets/32311723/f32f7024-f0f7-4bab-b6d8-ec3adc29f8a7)
![Simulator Screenshot - Apple TV 4K - 2024-05-24 at 08 57 38](https://github.com/getditto/DittoSwiftTools/assets/32311723/2a83da96-7f8c-4d3c-88da-b80ec1ccd64e)
![Simulator Screenshot - Apple TV 4K - 2024-05-24 at 08 58 12](https://github.com/getditto/DittoSwiftTools/assets/32311723/3624d957-7a0d-4750-9286-ffbba17ae154)
![Simulator Screenshot - Apple TV 4K - 2024-05-24 at 08 58 27](https://github.com/getditto/DittoSwiftTools/assets/32311723/19279b15-c5e4-406c-8cd8-a224503e924c)
![Simulator Screenshot - Apple TV 4K - 2024-05-24 at 08 59 09](https://github.com/getditto/DittoSwiftTools/assets/32311723/29db7a6b-920b-4608-8060-cf7061e69186)
![Simulator Screenshot - Apple TV 4K - 2024-05-24 at 08 59 51](https://github.com/getditto/DittoSwiftTools/assets/32311723/4ff3a336-e51a-448f-ab2b-fdad7aaf295b)
![Simulator Screenshot - Apple TV 4K - 2024-05-24 at 09 00 22](https://github.com/getditto/DittoSwiftTools/assets/32311723/6412b4a8-dec1-481d-98c8-311be4bd8545)
![Simulator Screenshot - Apple TV 4K - 2024-05-24 at 09 00 40](https://github.com/getditto/DittoSwiftTools/assets/32311723/b53bb82f-067e-431a-8543-150426ef7e4d)
![Simulator Screenshot - Apple TV 4K - 2024-05-24 at 09 00 57](https://github.com/getditto/DittoSwiftTools/assets/32311723/45d0181c-3c53-43c9-a8c2-2426f37a220f)
![Simulator Screenshot - Apple TV 4K - 2024-05-24 at 09 01 02](https://github.com/getditto/DittoSwiftTools/assets/32311723/0c6db272-3fde-47fe-b162-445d76b44450)
![Simulator Screenshot - iPad (10th generation) - 2024-05-24 at 08 55 22](https://github.com/getditto/DittoSwiftTools/assets/32311723/c2ac4d30-b238-4e46-bc22-c8d63fda3da1)
![Simulator Screenshot - iPad (10th generation) - 2024-05-24 at 08 57 45](https://github.com/getditto/DittoSwiftTools/assets/32311723/151abc9f-97f5-431e-a42e-8b85b86f9abe)
![Simulator Screenshot - iPad (10th generation) - 2024-05-24 at 08 58 13](https://github.com/getditto/DittoSwiftTools/assets/32311723/86d2c9d3-9059-4c4b-b9f1-6a0b0be5eeb8)
![Simulator Screenshot - iPad (10th generation) - 2024-05-24 at 08 58 29](https://github.com/getditto/DittoSwiftTools/assets/32311723/ca804e55-17a3-4d21-842a-63a0fd7c101a)
![Simulator Screenshot - iPad (10th generation) - 2024-05-24 at 08 59 10](https://github.com/getditto/DittoSwiftTools/assets/32311723/3479f93d-80a0-486a-8959-997f0cf62d1e)
![Simulator Screenshot - iPad (10th generation) - 2024-05-24 at 08 59 53](https://github.com/getditto/DittoSwiftTools/assets/32311723/7c094241-40cc-45f9-b255-3be70ae06f5b)
![Simulator Screenshot - iPad (10th generation) - 2024-05-24 at 09 00 24](https://github.com/getditto/DittoSwiftTools/assets/32311723/d667e4f5-2fcb-4f9f-b9d9-35b49229b47b)
![Simulator Screenshot - iPad (10th generation) - 2024-05-24 at 09 00 41](https://github.com/getditto/DittoSwiftTools/assets/32311723/7b732078-0135-420c-9eb3-2200870b641f)
![Simulator Screenshot - iPad (10th generation) - 2024-05-24 at 09 01 14](https://github.com/getditto/DittoSwiftTools/assets/32311723/82414f98-95de-4178-ae39-1c4f4f607347)
![Simulator Screenshot - iPhone Xs - 2024-05-24 at 08 55 24](https://github.com/getditto/DittoSwiftTools/assets/32311723/228e1380-708e-47f1-b00d-78792a1f5c69)
![Simulator Screenshot - iPhone Xs - 2024-05-24 at 08 57 47](https://github.com/getditto/DittoSwiftTools/assets/32311723/7abcaa0b-b26e-4606-9a93-52294809b270)
![Simulator Screenshot - iPhone Xs - 2024-05-24 at 08 58 14](https://github.com/getditto/DittoSwiftTools/assets/32311723/aa855d86-58aa-4526-b0f5-920a10fc535a)
![Simulator Screenshot - iPhone Xs - 2024-05-24 at 08 58 30](https://github.com/getditto/DittoSwiftTools/assets/32311723/5b621088-adb3-43df-b13d-9da74e5714a6)
![Simulator Screenshot - iPhone Xs - 2024-05-24 at 08 59 11](https://github.com/getditto/DittoSwiftTools/assets/32311723/f0c8bc63-bd0b-49d0-b597-3455554ea314)
![Simulator Screenshot - iPhone Xs - 2024-05-24 at 08 59 54](https://github.com/getditto/DittoSwiftTools/assets/32311723/9c74d744-8da8-4b31-828f-f03ca5079b17)
![Simulator Screenshot - iPhone Xs - 2024-05-24 at 09 00 25](https://github.com/getditto/DittoSwiftTools/assets/32311723/c2de4ce6-2f76-414d-8fc8-770d082ff98c)
![Simulator Screenshot - iPhone Xs - 2024-05-24 at 09 00 42](https://github.com/getditto/DittoSwiftTools/assets/32311723/8da1a24b-bc0d-4141-9da6-5b569c481b23)

2024-08-26 20:44 UTC, bplattenburg commented
@ErikEverson Thanks!

I'm hoping to merge the SDK version bump as its own PR in https://github.com/getditto/DittoSwiftTools/pull/138 so it gets called out in the changelog and we make sure to bump the major version here

2024-08-27 19:35 UTC, bplattenburg commented
From our conversation, this should also fix https://github.com/getditto/DittoSwiftTools/issues/139

2024-08-27 20:01 UTC, bplattenburg requested changes

2024-08-27 20:01 UTC, bplattenburg commented on Sources/DittoPresenceViewer/PresenceView.swift
> +@available(iOS 13, macOS 10.15, *)
I think we can drop the `iOS` piece here since we only support 14.0 and newer now

2024-08-28 13:25 UTC, bplattenburg approved these changes
Looks great!

2024-08-28 15:26 UTC, bplattenburg commented on Package.swift
> +        .macOS(.v11),
Can we remove macOS support again since its still broken? We've got a long term issue tracking adding it back

2024-08-28 15:27 UTC, merged